version: '3'
services:
  backend:
    container_name: backend
    restart: always
    build: ./backend/
    ports:
      - '8080:8080'
    volumes:
    # below is correct
    # problem is env.docker of backend is undefined
      - ./backend/app:/opt/develop/app/leaderboard
      - /opt/develop/app/leaderboard/node_modules
      - ./backend/app/env.docker:/opt/develop/app/leaderboard/.env
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend/
    ports:
      - '80:3000'
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    stdin_open: true
  mongo:
      container_name: mongodb
      image: mongo:latest
      restart: always
      environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
          MONGO_INITDB_DATABASE: db
      ports:
        - '27017'
      volumes:
          - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  redis:
    container_name: redis
    image: 'redis'
    ports:
      - '6379'
