db = db.getSiblingDB("leaderboard");
db.createCollection("db_collection");
db.createCollection("prize_collection");
db.db_collection.insertMany([
  {
    userName: "user1",
    country: "United States",
    gain: 2000,
    rank: 130,
    diff: 0,
  },
  {
    userName: "user2",
    country: "United States",
    gain: 3000,
    rank: 129,
    diff: 0,
  },
  {
    userName: "user3",
    country: "United States",
    gain: 4000,
    rank: 128,
    diff: 0,
  },
  {
    userName: "user4",
    country: "United States",
    gain: 5000,
    rank: 127,
    diff: 0,
  },
  {
    userName: "user5",
    country: "United States",
    gain: 6000,
    rank: 126,
    diff: 0,
  },
  {
    userName: "user6",
    country: "United States",
    gain: 7000,
    rank: 125,
    diff: 0,
  },
  {
    userName: "user7",
    country: "United States",
    gain: 8000,
    rank: 124,
    diff: 0,
  },
  {
    userName: "user8",
    country: "United States",
    gain: 9000,
    rank: 123,
    diff: 0,
  },
  {
    userName: "user9",
    country: "United States",
    gain: 10000,
    rank: 122,
    diff: 0,
  },
  {
    userName: "user10",
    country: "United States",
    gain: 11000,
    rank: 121,
    diff: 0,
  },
  {
    userName: "user11",
    country: "United States",
    gain: 12000,
    rank: 120,
    diff: 0,
  },
  {
    userName: "user12",
    country: "United States",
    gain: 13000,
    rank: 119,
    diff: 0,
  },
  {
    userName: "user13",
    country: "United States",
    gain: 14000,
    rank: 118,
    diff: 0,
  },
  {
    userName: "user14",
    country: "United States",
    gain: 15000,
    rank: 117,
    diff: 0,
  },
  {
    userName: "user15",
    country: "United States",
    gain: 16000,
    rank: 116,
    diff: 0,
  },
  {
    userName: "user16",
    country: "United States",
    gain: 17000,
    rank: 115,
    diff: 0,
  },
  {
    userName: "user17",
    country: "United States",
    gain: 18000,
    rank: 114,
    diff: 0,
  },
  {
    userName: "user18",
    country: "United States",
    gain: 19000,
    rank: 113,
    diff: 0,
  },
  {
    userName: "user19",
    country: "United States",
    gain: 20000,
    rank: 112,
    diff: 0,
  },
  {
    userName: "user20",
    country: "United States",
    gain: 21000,
    rank: 111,
    diff: 0,
  },
  {
    userName: "user21",
    country: "United States",
    gain: 22000,
    rank: 110,
    diff: 0,
  },
  {
    userName: "user22",
    country: "United States",
    gain: 23000,
    rank: 109,
    diff: 0,
  },
  {
    userName: "user23",
    country: "United States",
    gain: 24000,
    rank: 108,
    diff: 0,
  },
  {
    userName: "user24",
    country: "United States",
    gain: 25000,
    rank: 107,
    diff: 0,
  },
  {
    userName: "user25",
    country: "United States",
    gain: 26000,
    rank: 106,
    diff: 0,
  },
  {
    userName: "user26",
    country: "United States",
    gain: 27000,
    rank: 105,
    diff: 0,
  },
  {
    userName: "user27",
    country: "United States",
    gain: 28000,
    rank: 104,
    diff: 0,
  },
  {
    userName: "user28",
    country: "United States",
    gain: 29000,
    rank: 103,
    diff: 0,
  },
  {
    userName: "user29",
    country: "United States",
    gain: 30000,
    rank: 102,
    diff: 0,
  },
  {
    userName: "user30",
    country: "United States",
    gain: 31000,
    rank: 101,
    diff: 0,
  },
  {
    userName: "user31",
    country: "United States",
    gain: 32000,
    rank: 100,
    diff: 0,
  },
  {
    userName: "user32",
    country: "United States",
    gain: 33000,
    rank: 99,
    diff: 0,
  },
  {
    userName: "user33",
    country: "United States",
    gain: 34000,
    rank: 98,
    diff: 0,
  },
  {
    userName: "user34",
    country: "United States",
    gain: 35000,
    rank: 97,
    diff: 0,
  },
  {
    userName: "user35",
    country: "United States",
    gain: 36000,
    rank: 96,
    diff: 0,
  },
  {
    userName: "user36",
    country: "United States",
    gain: 37000,
    rank: 95,
    diff: 0,
  },
  {
    userName: "user37",
    country: "United States",
    gain: 38000,
    rank: 94,
    diff: 0,
  },
  {
    userName: "user38",
    country: "United States",
    gain: 39000,
    rank: 93,
    diff: 0,
  },
  {
    userName: "user39",
    country: "United States",
    gain: 40000,
    rank: 92,
    diff: 0,
  },
  {
    userName: "user40",
    country: "United States",
    gain: 41000,
    rank: 91,
    diff: 0,
  },
  {
    userName: "user41",
    country: "United States",
    gain: 42000,
    rank: 90,
    diff: 0,
  },
  {
    userName: "user42",
    country: "United States",
    gain: 43000,
    rank: 89,
    diff: 0,
  },
  {
    userName: "user43",
    country: "United States",
    gain: 44000,
    rank: 88,
    diff: 0,
  },
  {
    userName: "user44",
    country: "United States",
    gain: 45000,
    rank: 87,
    diff: 0,
  },
  {
    userName: "user45",
    country: "United States",
    gain: 46000,
    rank: 86,
    diff: 0,
  },
  {
    userName: "user46",
    country: "United States",
    gain: 47000,
    rank: 85,
    diff: 0,
  },
  {
    userName: "user47",
    country: "United States",
    gain: 48000,
    rank: 84,
    diff: 0,
  },
  {
    userName: "user48",
    country: "United States",
    gain: 49000,
    rank: 83,
    diff: 0,
  },
  {
    userName: "user49",
    country: "United States",
    gain: 50000,
    rank: 82,
    diff: 0,
  },
  {
    userName: "user50",
    country: "United States",
    gain: 51000,
    rank: 81,
    diff: 0,
  },
  {
    userName: "user51",
    country: "United States",
    gain: 52000,
    rank: 80,
    diff: 0,
  },
  {
    userName: "user52",
    country: "United States",
    gain: 53000,
    rank: 79,
    diff: 0,
  },
  {
    userName: "user53",
    country: "United States",
    gain: 54000,
    rank: 78,
    diff: 0,
  },
  {
    userName: "user54",
    country: "United States",
    gain: 55000,
    rank: 77,
    diff: 0,
  },
  {
    userName: "user55",
    country: "United States",
    gain: 56000,
    rank: 76,
    diff: 0,
  },
  {
    userName: "user56",
    country: "United States",
    gain: 57000,
    rank: 75,
    diff: 0,
  },
  {
    userName: "user57",
    country: "United States",
    gain: 58000,
    rank: 74,
    diff: 0,
  },
  {
    userName: "user58",
    country: "United States",
    gain: 59000,
    rank: 73,
    diff: 0,
  },
  {
    userName: "user59",
    country: "United States",
    gain: 60000,
    rank: 72,
    diff: 0,
  },
  {
    userName: "user60",
    country: "United States",
    gain: 61000,
    rank: 71,
    diff: 0,
  },
  {
    userName: "user61",
    country: "United States",
    gain: 62000,
    rank: 70,
    diff: 0,
  },
  {
    userName: "user62",
    country: "United States",
    gain: 63000,
    rank: 69,
    diff: 0,
  },
  {
    userName: "user63",
    country: "United States",
    gain: 64000,
    rank: 68,
    diff: 0,
  },
  {
    userName: "user64",
    country: "United States",
    gain: 65000,
    rank: 67,
    diff: 0,
  },
  {
    userName: "user65",
    country: "United States",
    gain: 66000,
    rank: 66,
    diff: 0,
  },
  {
    userName: "user66",
    country: "United States",
    gain: 67000,
    rank: 65,
    diff: 0,
  },
  {
    userName: "user67",
    country: "United States",
    gain: 68000,
    rank: 64,
    diff: 0,
  },
  {
    userName: "user68",
    country: "United States",
    gain: 69000,
    rank: 63,
    diff: 0,
  },
  {
    userName: "user69",
    country: "United States",
    gain: 70000,
    rank: 62,
    diff: 0,
  },
  {
    userName: "user70",
    country: "United States",
    gain: 71000,
    rank: 61,
    diff: 0,
  },
  {
    userName: "user71",
    country: "United States",
    gain: 72000,
    rank: 60,
    diff: 0,
  },
  {
    userName: "user72",
    country: "United States",
    gain: 73000,
    rank: 59,
    diff: 0,
  },
  {
    userName: "user73",
    country: "United States",
    gain: 74000,
    rank: 58,
    diff: 0,
  },
  {
    userName: "user74",
    country: "United States",
    gain: 75000,
    rank: 57,
    diff: 0,
  },
  {
    userName: "user75",
    country: "United States",
    gain: 76000,
    rank: 56,
    diff: 0,
  },
  {
    userName: "user76",
    country: "United States",
    gain: 77000,
    rank: 55,
    diff: 0,
  },
  {
    userName: "user77",
    country: "United States",
    gain: 78000,
    rank: 54,
    diff: 0,
  },
  {
    userName: "user78",
    country: "United States",
    gain: 79000,
    rank: 53,
    diff: 0,
  },
  {
    userName: "user79",
    country: "United States",
    gain: 80000,
    rank: 52,
    diff: 0,
  },
  {
    userName: "user80",
    country: "United States",
    gain: 81000,
    rank: 51,
    diff: 0,
  },
  {
    userName: "user81",
    country: "United States",
    gain: 82000,
    rank: 50,
    diff: 0,
  },
  {
    userName: "user82",
    country: "United States",
    gain: 83000,
    rank: 49,
    diff: 0,
  },
  {
    userName: "user83",
    country: "United States",
    gain: 84000,
    rank: 48,
    diff: 0,
  },
  {
    userName: "user84",
    country: "United States",
    gain: 85000,
    rank: 47,
    diff: 0,
  },
  {
    userName: "user85",
    country: "United States",
    gain: 86000,
    rank: 46,
    diff: 0,
  },
  {
    userName: "user86",
    country: "United States",
    gain: 87000,
    rank: 45,
    diff: 0,
  },
  {
    userName: "user87",
    country: "United States",
    gain: 88000,
    rank: 44,
    diff: 0,
  },
  {
    userName: "user88",
    country: "United States",
    gain: 89000,
    rank: 43,
    diff: 0,
  },
  {
    userName: "user89",
    country: "United States",
    gain: 90000,
    rank: 42,
    diff: 0,
  },
  {
    userName: "user90",
    country: "United States",
    gain: 91000,
    rank: 41,
    diff: 0,
  },
  {
    userName: "user91",
    country: "United States",
    gain: 92000,
    rank: 40,
    diff: 0,
  },
  {
    userName: "user92",
    country: "United States",
    gain: 93000,
    rank: 39,
    diff: 0,
  },
  {
    userName: "user93",
    country: "United States",
    gain: 94000,
    rank: 38,
    diff: 0,
  },
  {
    userName: "user94",
    country: "United States",
    gain: 95000,
    rank: 37,
    diff: 0,
  },
  {
    userName: "user95",
    country: "United States",
    gain: 96000,
    rank: 36,
    diff: 0,
  },
  {
    userName: "user96",
    country: "United States",
    gain: 97000,
    rank: 35,
    diff: 0,
  },
  {
    userName: "user97",
    country: "United States",
    gain: 98000,
    rank: 34,
    diff: 0,
  },
  {
    userName: "user98",
    country: "United States",
    gain: 99000,
    rank: 33,
    diff: 0,
  },
  {
    userName: "user99",
    country: "United States",
    gain: 100000,
    rank: 32,
    diff: 0,
  },
  {
    userName: "user100",
    country: "United States",
    gain: 101000,
    rank: 31,
    diff: 0,
  },
  {
    userName: "user101",
    country: "United States",
    gain: 102000,
    rank: 30,
    diff: 0,
  },
  {
    userName: "user102",
    country: "United States",
    gain: 103000,
    rank: 29,
    diff: 0,
  },
  {
    userName: "user103",
    country: "United States",
    gain: 104000,
    rank: 28,
    diff: 0,
  },
  {
    userName: "user104",
    country: "United States",
    gain: 105000,
    rank: 27,
    diff: 0,
  },
  {
    userName: "user105",
    country: "United States",
    gain: 106000,
    rank: 26,
    diff: 0,
  },
  {
    userName: "user106",
    country: "United States",
    gain: 107000,
    rank: 25,
    diff: 0,
  },
  {
    userName: "user107",
    country: "United States",
    gain: 108000,
    rank: 24,
    diff: 0,
  },
  {
    userName: "user108",
    country: "United States",
    gain: 109000,
    rank: 23,
    diff: 0,
  },
  {
    userName: "user109",
    country: "United States",
    gain: 110000,
    rank: 22,
    diff: 0,
  },
  {
    userName: "user110",
    country: "United States",
    gain: 111000,
    rank: 21,
    diff: 0,
  },
  {
    userName: "user111",
    country: "United States",
    gain: 112000,
    rank: 20,
    diff: 0,
  },
  {
    userName: "user112",
    country: "United States",
    gain: 113000,
    rank: 19,
    diff: 0,
  },
  {
    userName: "user113",
    country: "United States",
    gain: 114000,
    rank: 18,
    diff: 0,
  },
  {
    userName: "user114",
    country: "United States",
    gain: 115000,
    rank: 17,
    diff: 0,
  },
  {
    userName: "user115",
    country: "United States",
    gain: 116000,
    rank: 16,
    diff: 0,
  },
  {
    userName: "user116",
    country: "United States",
    gain: 117000,
    rank: 15,
    diff: 0,
  },
  {
    userName: "user117",
    country: "United States",
    gain: 118000,
    rank: 14,
    diff: 0,
  },
  {
    userName: "user118",
    country: "United States",
    gain: 119000,
    rank: 13,
    diff: 0,
  },
  {
    userName: "user119",
    country: "United States",
    gain: 120000,
    rank: 12,
    diff: 0,
  },
  {
    userName: "user120",
    country: "United States",
    gain: 121000,
    rank: 11,
    diff: 0,
  },
  {
    userName: "user121",
    country: "United States",
    gain: 122000,
    rank: 10,
    diff: 0,
  },
  {
    userName: "user122",
    country: "United States",
    gain: 123000,
    rank: 9,
    diff: 0,
  },
  {
    userName: "user123",
    country: "United States",
    gain: 124000,
    rank: 8,
    diff: 0,
  },
  {
    userName: "user124",
    country: "United States",
    gain: 125000,
    rank: 7,
    diff: 0,
  },
  {
    userName: "user125",
    country: "United States",
    gain: 126000,
    rank: 6,
    diff: 0,
  },
  {
    userName: "user126",
    country: "United States",
    gain: 127000,
    rank: 5,
    diff: 0,
  },
  {
    userName: "user127",
    country: "United States",
    gain: 128000,
    rank: 4,
    diff: 0,
  },
  {
    userName: "user128",
    country: "United States",
    gain: 129000,
    rank: 3,
    diff: 0,
  },
  {
    userName: "user129",
    country: "United States",
    gain: 130000,
    rank: 2,
    diff: 0,
  },
  {
    userName: "user130",
    country: "United States",
    gain: 131000,
    rank: 1,
    diff: 0,
  },
]);
